Initial bootstrap
Wolox/react-bootstrap pull request #1
Opened 2017-09-18 18:01 UTC by NaomiFPassarelli

- Create initial bootstrap with yeoman basic structure and packages needed
- Added possibility to choose optional packages (carrousel, moment, etc)

2017-09-18 20:29 UTC, SKOLZ requested changes

2017-09-18 20:29 UTC, SKOLZ commented on generators/app/templates/_package.json
> +  "version": "0.0.0",
is it correct to have 0.0.0? I think we should set it to at least 0.1.0

2017-09-18 20:29 UTC, SKOLZ commented on generators/app/templates/_package.json
> +    <% if (includeAphrodite && !includeRadium) {%>
remove aphrodite

2017-09-18 20:29 UTC, SKOLZ commented on generators/app/templates/_package.json
> +    if (!includeAphrodite && includeRadium) {%>
remove radium

2017-09-18 20:29 UTC, SKOLZ commented on generators/app/templates/_package.json
> +    if (includeMobileDetect) {%>
I don't think this is necesary, do we have an example of a project where we are using it?

2017-09-18 20:29 UTC, SKOLZ commented on generators/app/templates/_package.json
> +    if (includePostcss) {%>
we should add this by default, I would also add with it the autoprefixer(https://github.com/postcss/autoprefixer) and the sprites(https://github.com/2createStudio/postcss-sprites) plugins

2017-09-18 20:29 UTC, SKOLZ commented on generators/app/templates/_package.json
> +    if (includeReactResponsive) {%>
I would remove this from the selection. This is not used very often, I would use that library only  when we need it or directly define a utils function to determine a phone width and apply decitions based on that

2017-09-19 18:12 UTC, mcallegari10 requested changes

2017-09-19 18:12 UTC, mcallegari10 commented on generators/app/templates/_package.json
> +  "version": "0.0.0",
I agree, I'd use 1.0.0 instead

2017-09-19 18:12 UTC, mcallegari10 commented on generators/app/templates/public/index.html
> +    -->
I'd delete this comment. Otherwise, it makes this a copy paste of create-react-app and we don't want that :smile:

2017-09-19 18:12 UTC, mcallegari10 commented on generators/app/templates/src/app/components/Routes/components/AuthenticatedRoute.js
> +debugger;
![](http://www.reactiongifs.com/r/wsod.gif)

2017-09-19 18:14 UTC, SKOLZ requested changes

2017-09-19 18:14 UTC, SKOLZ commented on generators/app/templates/_package.json
> +    if (includeReselect) {%>
include this by default

2017-09-19 18:14 UTC, SKOLZ commented on generators/app/templates/public/index.html
> +  <!--
remove this comment

2017-09-19 18:14 UTC, SKOLZ commented on generators/app/templates/public/index.html
> +  <!--
remove this comment

2017-09-19 18:14 UTC, SKOLZ commented on generators/app/templates/_package.json
> +    if (includeReselect) {%>
add this by default

2017-09-19 18:14 UTC, SKOLZ commented on generators/app/templates/_package.json
> +    "react-router-redux": "^5.0.0-alpha.6",
I would add this one if we are using redux or the react router 4 if we are not.

2017-09-19 18:14 UTC, SKOLZ commented on generators/app/templates/public/index.html
> +  <!--
remove comment

2017-09-19 18:14 UTC, SKOLZ commented on generators/app/templates/public/index.html
> +  <!--
remove comment

2017-09-19 18:14 UTC, SKOLZ commented on generators/app/templates/src/app/components/Button/index.js
> +import Radium from "radium";
no radium, use css-modules instead

2017-09-20 12:03 UTC, SKOLZ requested changes

2017-09-20 12:03 UTC, SKOLZ commented on generators/app/templates/eslintrc.js
> +  plugins: ['react', 'prettier', 'flowtype'],
we won't be using typed js

2017-09-20 12:03 UTC, SKOLZ commented on generators/app/templates/eslintrc.js
> +    'prettier/flowtype',
same

2017-09-20 12:03 UTC, SKOLZ commented on generators/app/templates/src/app/components/Checkbox/index.js
> +import Radium from "radium";
change radium to css modules here too please

2017-09-20 12:03 UTC, SKOLZ commented on generators/app/templates/src/app/components/Label/index.js
> +import Radium from "radium";
change radium to css modules here too please

2017-09-20 12:03 UTC, SKOLZ commented on generators/app/templates/src/app/components/RadioButton/index.js
> +import Radium from "radium";
change radium to css modules here too please

2017-09-20 13:30 UTC, pabloferro submitted a review, later dismissed
Fix the package version and the debugger and 👍

2017-09-25 14:25 UTC, SKOLZ submitted a review, later dismissed

2017-09-25 14:38 UTC, mcallegari10 submitted a review, later dismissed

2017-09-25 14:53 UTC, sbalay requested changes
I guess this is enough for a first approach but we still need to run `create-react-app` here

2017-09-25 14:53 UTC, sbalay commented on generators/app/index.js
> +        type: "confirm",
I'd remove all these confirms and decide which libraries we want to always include and which libraries we don't.

When you kickoff a project you probably don't know if you will need recharts, carousel, mobileDetect, etc. Forcing a decision over something you don't know is more a problem than a solution.

2017-09-25 14:53 UTC, sbalay commented on generators/app/index.js
> +"use strict";
this file is huge

2017-09-25 14:53 UTC, sbalay commented on generators/app/index.js
> +        function hasFeature(feat, prop) {
What's the goal of this function?

2017-09-25 14:53 UTC, sbalay commented on generators/app/index.js
> +    this.fs.copyTpl(
Are all these files templates? Use `this.fs.copy` if they are not

2017-09-25 14:53 UTC, sbalay commented on generators/app/index.js
> +      this.templatePath("public/index.html"),
We should be consistent with the naming of the templates. The template of `package.json` starts with `_`.  Use the same convention in all the files

2017-09-29 19:52 UTC, SKOLZ commented
we decided to merge this to have something to work with

2017-09-29 19:52 UTC, merged