Add jenkins
Wolox/react-bootstrap pull request #102
Opened 2020-01-29 17:51 UTC by tomiir

## Summary
Added jenkins and config files

2020-01-30 16:11 UTC, facucompe commented on Jenkinsfile
> +}
Perdón, es un TOC
```suggestion
}

```

2020-01-30 17:32 UTC, damfinkel requested changes

2020-01-30 17:32 UTC, damfinkel commented on .woloxci/Dockerfile
> +FROM node:10.11.0-alpine
I'd use 12.14.1-alpine, which is the latest stable release: https://nodejs.org/en/

2020-02-07 18:52 UTC, damfinkel approved these changes

2020-02-07 18:57 UTC, pabloferro approved these changes

2020-02-14 13:46 UTC, carlosbollero approved these changes
A comment for further developments.
What about adding a step to create a new project, build and run it, then check there is no errors?
This way we will be sure any change we do, doesn't break future bootstrapped projects.
What do you think? @tomiir @pabloferro @damfinkel

2020-02-18 14:40 UTC, merged

2020-02-18 14:40 UTC, tomiir commented
@pabloferro  @damfinkel  I'm merging this but I think what @carlosbollero  makes a lot of sense. Will add a card to the trello board so we don't forget about this.