Registration
Wolox/react-bootstrap pull request #134
Opened 2020-06-17 20:15 UTC by carlosbollero

*...soon*

2020-06-23 18:45 UTC, mcallegari10 approved these changes

2020-06-26 17:50 UTC, tomiir commented on generators/app/templates/src/app/screens/Registration/components/FormStep/styles.module.scss
> +}
missing EOF

2020-06-29 21:03 UTC, mcallegari10 approved these changes

2020-06-29 21:03 UTC, mcallegari10 commented on generators/app/templates/src/app/screens/Registration/index.tsx
> +  const { handleChange, handleSubmit, values, errors, isValid } = formik;
Can't you destructure this variables in the first line? Like:

```suggestion
  const { handleChange, handleSubmit, values, errors, isValid } = useFormik({ initialValues, onSubmit: handleFormSubmit, validate });
```

2020-06-29 21:03 UTC, mcallegari10 commented on generators/app/templates/src/app/screens/Registration/constants.ts
> +    ...step.fields.reduce((acu: any, field: any) => ({ ...acu, [field.name]: field.initialValue }), {})
Add a `TODO`, I think we can type this more strongly, like declaring a `field` interface with all the posible validations

2020-06-30 19:14 UTC, FrankIglesias requested changes

2020-06-30 19:14 UTC, FrankIglesias commented on generators/app/templates/src/app/screens/Registration/index.tsx
> +      setStep(currentStep - 1);
```suggestion
      setStep(Math.max(0,currentStep));
```

2020-06-30 19:14 UTC, FrankIglesias commented on generators/app/templates/src/app/screens/Registration/index.tsx
> +      setStep(currentStep + 1);
```suggestion
      setStep(Math.min(currentStep + 1, steps.length-1));
```

2020-06-30 19:14 UTC, FrankIglesias commented on generators/app/templates/src/app/screens/Registration/index.tsx
> +        <button className={styles.button} type="button" onClick={handlePrevStep} disabled={currentStep === 0}>
```suggestion
        <button className={styles.button} type="button" onClick={handlePrevStep} disabled={!currentStep}>
```

2020-06-30 19:14 UTC, FrankIglesias commented on generators/app/templates/src/app/screens/Registration/validations.ts
> +};
missing i18n

2020-06-30 19:14 UTC, FrankIglesias commented on generators/app/templates/src/app/screens/Registration/validations.ts
> +      }
This can be replaced  with a filter

2021-01-11 20:34 UTC, pabloferro commented
This has too many conflicts and is outdated. We should revisit this feature in another PR.

2021-01-11 20:34 UTC, closed without merging