Implement immer & some lint fixes
Wolox/react-bootstrap pull request #163
Opened 2021-03-31 02:42 UTC by alejobh

## Summary
* Fixed broken bootstrap README
* Updated stylelint dependencies
* Added and edited useful project commands:
`ts-check`: Checks for typescript errors.
`test`: Updated for ci purposes
`test-interactive`: Same as `test` but keeps on interactive mode
`test-no-coverage`: Same as `test-interactive` but shows no files coverage.
* Removed `import React` from every appearance (not necessary now because @pabloferro updated react version and our eslint rules are mostly up to date thanks to @damfinkel). BUT i had to leave a TODO about a new rule that needs to be added to eslint wolox rules package, but i dont really know how to deal the versioning because its a big breaking change.
* Added **immer** to handle immutability on reducers, with a new typing way using type annotations.

## Known issues
We have to update linters from bootstrap project directly because it's parsing when saving in the wrong way when working on templates.
Also we need to find a way to apply the generated project lint config into the bootstrap itself to code directly in the bootstrap in a safe way without needing to generate a new project and work on there.

## Screenshots
![image](https://user-images.githubusercontent.com/15016271/113082650-78a7f480-91a0-11eb-9353-0dbe24997655.png)

![image](https://user-images.githubusercontent.com/15016271/113082566-56ae7200-91a0-11eb-8ac3-66f272631fca.png)

2021-04-05 14:30 UTC, pabloferro requested changes
Awesome work 🎉 

I left a few small comments.

2021-04-05 14:30 UTC, pabloferro commented on generators/app/steps/CustomizableSteps/constants.js
> +// TODO: What to do here about dev dependencies when using customizable, why is plop here? shouldn't it be on generators/app/constants.js ?
I think we are always using customizable by default for now.
After this remove the comment.

2021-04-05 14:30 UTC, pabloferro commented on generators/app/tasks/fileCreators.js
> +    'ts-check': 'tsc',
```suggestion
    'tsc': 'tsc',
```
Maybe I'd rename the name just for clarity. Not sure 🙃

2021-04-05 14:30 UTC, pabloferro commented on generators/app/templates/templates/component/index.test.tsx.hbs
> +
I'd move the snapshot test to the beginning.

2021-04-05 20:41 UTC, pabloferro commented on generators/app/constants.js
> +  'immer@^9.0.1',
Move to customizable dependencies (NOT dev dep)

2021-04-13 13:58 UTC, pabloferro approved these changes
Nice work! 🎉

2021-04-13 13:59 UTC, pabloferro commented
https://github.com/Wolox/react-bootstrap/pull/163

2021-04-19 14:52 UTC, damfinkel approved these changes

2021-04-21 23:13 UTC, merged