Create component Spinner
Wolox/react-bootstrap pull request #28
Opened 2018-08-09 00:21 UTC by nicolobruno

## Description

- WrapSpinner contain loading and use https://github.com/KyleAMathews/react-spinkit.
- Updated README with the use of component

Use it in this way:

```js
export default withSpinner({
  type: circle,
  classNameLoading: styles.spinner,
  classNameContainer: styles.container
});
```
## Screenshots

![loading](https://user-images.githubusercontent.com/28309103/43871052-1d091372-9b51-11e8-8761-9d090cf988fd.gif)

![storyloading](https://user-images.githubusercontent.com/28309103/44302562-836c2e80-a301-11e8-816b-fbcbb3ef955d.gif)

2018-08-09 00:37 UTC, FrankIglesias requested changes

2018-08-09 00:37 UTC, FrankIglesias commented on README.md
> +```
```js

2018-08-09 00:37 UTC, FrankIglesias commented on README.md
> +  WrappedComponent: SearchBarContainer,
A nice approach would be 
```js 
export default  withSpinner({idLoading: 1, classNameContainer: styles.spinner})(SearchBarContainer)
```
This is a classic pattern used by many packages. `ẀithSpinner` must return a function that receives a component and returns another one. The param will be like the wrapped component.

2018-08-09 00:37 UTC, FrankIglesias commented on README.md
> +
delete this 3 lines below

2018-08-09 00:37 UTC, FrankIglesias commented on README.md
> +Here you can see all the spinner models that this library has http://kyleamathews.github.io/react-spinkit/
are we using the whole number of models for this spinners? I'd be nice to have a demo of each of them and the corresponding loading id

2018-08-14 21:51 UTC, FrankIglesias requested changes

2018-08-14 21:51 UTC, FrankIglesias commented on README.md
> +```
use ```js instead to highlight the text

2018-08-15 01:22 UTC, FrankIglesias approved these changes

2018-08-22 20:56 UTC, damfinkel requested changes

2018-08-22 20:56 UTC, damfinkel commented on README.md
> +The component contain this props:
contains these props

2018-08-22 20:56 UTC, damfinkel commented on README.md
> +  <label className={styles.labelSearch}>
this needs an html-for so when clicking the label, we also focus the input

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_label

2018-08-22 20:56 UTC, damfinkel commented on README.md
> +Contain this component:
Contains this component

2018-08-22 20:56 UTC, damfinkel commented on README.md
> +export default withSpinner({
The wrapped component is missing here. Shouldn it be 
```
export default withSpinner({
WrappedComponent
...
})()
```
?

2018-08-22 20:56 UTC, damfinkel commented on generators/app/templates/src/app/components/Spinner/components/constants.js
> +export const TYPE_SPINNER = {
change to array of strings so we can do:

`<Loading id="three-bounce">`

2018-08-22 20:56 UTC, damfinkel commented on generators/app/templates/src/app/components/Spinner/components/loading.js
> +function Loading({ className, id, color }) {
change id to type

2018-08-22 20:56 UTC, damfinkel commented on generators/app/templates/src/app/components/Spinner/components/loading.js
> +  id: PropTypes.number,
type: PropTypes.oneOf(TYPE_SPINNER)

2018-08-22 20:56 UTC, damfinkel commented on generators/app/templates/src/app/components/Spinner/index.js
> +  function Spinner(props) {
{ loading }

2018-08-22 20:56 UTC, damfinkel commented on generators/app/templates/stories/components.js
> +storiesOf('Spinner', module).add('Id Loading 1', () => (
change all these for names instead of ids

2018-08-22 20:56 UTC, damfinkel commented on generators/app/templates/stories/styles.scss
> +}
enter

2018-08-27 13:00 UTC, damfinkel approved these changes

2018-08-27 13:56 UTC, merged