Add propTypes in the README
Wolox/react-bootstrap pull request #30
Opened 2018-08-28 02:59 UTC by nicolobruno

## Description

- Add proTypes in the components in the README.
- Add description of TextArea component in the README.

2018-09-15 00:04 UTC, FrankIglesias requested changes

2018-09-15 00:04 UTC, FrankIglesias commented on generators/app/templates/src/app/components/TextArea/index.js
> +  className: PropTypes.string,
add a default prop for this like ''

2018-09-16 17:00 UTC, nicolobruno commented
I had to add `"eslint-config-react-app": "^2.1.0" ` for run lint. This updated the package-lock.json. Please we check this is ok

2018-10-01 14:54 UTC, FrankIglesias approved these changes

2018-10-01 22:26 UTC, damfinkel requested changes

2018-10-01 22:26 UTC, damfinkel commented on README.md
> +| | self-stretch | ``` alingn-self: self-stretch ```|
align-self

2018-10-01 22:26 UTC, damfinkel commented on README.md
> +| layout.scss| row | ``` display: flex flex-direction: row ```|
Some of these properties change depending on which flex-direction they have. For example:
`row middle` is `align-items: center;` and
`column middle` is `justify-content: center;`

Maybe we could have one row per each of these combinations for those classes that change

2018-10-01 22:26 UTC, damfinkel commented on README.md
> +// Is equals a this:
Is equal to this:

2018-10-01 22:26 UTC, damfinkel commented on generators/app/templates/src/app/components/Spinner/index.js
> +  function Spinner({ loading, props }) {
`function Spinner({ loading, ...props }) {`

2018-10-08 17:35 UTC, damfinkel approved these changes

2018-10-08 19:05 UTC, merged