Create Menu component
Wolox/react-bootstrap pull request #53
Opened 2018-12-10 23:19 UTC by nicolobruno

# Description

- Create Menu component generic

## Screenshots 

`Pending`

2018-12-19 17:10 UTC, mmamaniwolox commented on generators/app/templates/src/app/components/Menu/components/MenuItem/components/MenuSubItem/index.js
> +  handleSubItemSelected = () => {
Could be `handleSubItemSelected = () => this.props.onSubItemSelected(this.props.subItem);` ?

2018-12-19 17:10 UTC, mmamaniwolox commented on generators/app/templates/src/app/components/Menu/components/MenuItem/components/MenuSubItem/styles.module.scss
> +@import '../../../../../../../scss/variables/_colors';
We do need relative imports :P

2018-12-19 17:10 UTC, mmamaniwolox commented on generators/app/templates/src/app/components/Menu/components/MenuItem/index.js
> +  handleMenuItemSelected = () => {
Could be `handleMenuItemSelected = () => this.props.handleItemSelected(this.props.menuItem);` ?

2018-12-19 17:10 UTC, mmamaniwolox commented on generators/app/templates/src/app/components/Menu/components/MenuItem/index.js
> +    const isActive = this.props.currentSelectedItemId === this.props.menuItem.id;
I think you could move this line below and use `currentSelectedItemId` and `menuItem` without `this.props`

2018-12-19 17:10 UTC, mmamaniwolox commented on generators/app/templates/src/app/components/Menu/components/MenuItem/styles.module.scss
> +}
Add a tailing line

2018-12-19 17:10 UTC, mmamaniwolox commented on generators/app/templates/src/app/components/Menu/index.js
> +    if (window.location.pathname !== selectedItem.path) {
Can this logic be moved to actions file? I haven't seen this in other projects

2018-12-19 17:10 UTC, mmamaniwolox commented on generators/app/templates/src/app/components/Menu/index.js
> +  handleSubItemSelected: selectedSubItem => {
Can be `handleSubItemSelected: selectedSubItem => dispatch(push({pathname: selectedSubItem.path})`?

2019-01-11 01:26 UTC, FrankIglesias requested changes

2019-01-11 01:26 UTC, FrankIglesias commented on generators/app/templates/src/app/components/Menu/components/MenuItem/components/MenuSubItem/styles.module.scss
> +  padding: 10px;
use shorthand for paddings

2019-01-11 01:26 UTC, FrankIglesias commented on generators/app/templates/src/app/components/Menu/styles.module.scss
> +  box-shadow: 2px 0 4px 0 rgba($black, 0.25);
use color variable

2019-01-18 15:05 UTC, briangerez commented on generators/app/templates/src/app/components/Menu/propTypes.js
> +export const menuItemPropTypes = PropTypes.shape({
There is already a menuItemPropTypes in `src / app / components / Menu / components / MenuItem / propTypes.js` ?

2019-04-01 14:56 UTC, closed without merging