Navbar
Wolox/react-bootstrap pull request #54
Opened 2018-12-11 19:34 UTC by mmamaniwolox

## Summary 
- Added a navbar with Auth Buttons, App Logo and Nav links

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +function AuthButtons({ isLoggedIn, logoutAction, loginAction, registerAction }) {
I'd add the traductions in i18n. In the Login we are doing it.

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/index.js
> +export default connect()(Navbar);
Delete `connect()` and `import { connect } from 'react-redux'`. It will be added when necessary

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/styles.module.scss
> +.container {
In the bootstrap we use classGeneric https://github.com/Wolox/react-bootstrap/blob/development/generators/app/templates/docs/BaseStyles.md.

In this case you can use `className={'row middle space-between full-width ${styles.container}'}` and delete in the class container this all styles

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/styles.module.scss
> +.log-buttons {
In this case you can use `className="row"` and delete this class

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/styles.module.scss
> +.routes-list {
In this case you can use `className="row space-around"` and delete this class

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/components/LinkList/index.js
> +  routesList: PropTypes.shape({
I'd extract this propType into the `LinkList/propTypes.js`

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +  loginAction: PropTypes.func.isRequired,
I'd replace for `handleLogin`. @damfinkel @carlosbollero What do you think

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +  logoutAction: PropTypes.func.isRequired,
I'd replace for `handleLogout`. @damfinkel @carlosbollero What do you think

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/index.js
> +  loginAction = () => {
Same `handleLogin`

2018-12-12 23:21 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/index.js
> +  logoutAction = () => {
Same `handleLogout`

2019-01-11 01:24 UTC, FrankIglesias requested changes

2019-01-11 01:24 UTC, FrankIglesias commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +    <div className={`row ${styles.authButtons} ${authStyle || ''}`}>
authStyle can be defined as a default prop

2019-01-11 01:24 UTC, FrankIglesias commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +        <button className={`${styles.button} ${authButtonStyle || ''}`} onClick={onLogout} type="button">
same this

2019-01-11 01:24 UTC, FrankIglesias commented on generators/app/templates/src/app/components/Navbar/components/LinkList/index.js
> +    <div className={`row space-around ${styles.linkList} ${routesStyle || ''}`}>
default for this

2019-01-11 01:24 UTC, FrankIglesias commented on generators/app/templates/src/app/components/Navbar/index.js
> +          <img className={`${styles.title} ${logoStyle || ''}`} src={title.image} alt={title.desc} />
define a default prop for this

2019-01-11 01:24 UTC, FrankIglesias commented on generators/app/templates/src/app/components/Navbar/index.js
> +      <div className={`row middle full-width ${styles.navbarContainer} ${navbarStyle || ''}`}>
same here

2019-01-11 01:24 UTC, FrankIglesias commented on generators/app/templates/src/app/components/Navbar/styles.module.scss
> +  z-index: 999999;
sure this can be done with just a 1 as value?

2019-01-11 01:24 UTC, FrankIglesias commented on generators/app/templates/src/app/components/Navbar/styles.module.scss
> +  &:nth-last-child(1) {
first child

2019-01-11 16:14 UTC, mmamaniwolox commented on generators/app/templates/src/app/components/Navbar/styles.module.scss
> +  &:nth-last-child(1) {
It is the last one 🤔  I needed to select the number starting from the end

2019-01-11 16:14 UTC, mmamaniwolox commented on generators/app/templates/src/app/components/Navbar/styles.module.scss
> +  z-index: 999999;
Yes, there is also a sidebar and modals

2019-01-14 01:47 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/index.js
> +        <button onClick={this.handleRouteClick(APP_ROUTES.HOME)} type="button">
If this is only redirection you can use `Link` of `react-router-dom`. It do not need to dispatch a function for change the path in the store. It do alone

2019-01-14 01:47 UTC, nicolobruno commented on generators/app/templates/src/app/components/Routes/styles.module.scss
> +  flex-direction: column;
You can use `className="column"` and delete this:
```
display: flex;
flex-direction: column;
```

2019-01-14 01:47 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/components/LinkList/index.js
> +    <div className={`row space-around ${styles.linkList} ${routesStyle}`}>
Mmm I'd would put `row space-around` in default className. For not limit the style of component

2019-01-14 01:47 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/components/LinkList/index.js
> +  routeStyle: PropTypes.string,
Mmm by convention we name the styles with className, in this case I put `routeClassName` and `routesContainerClassName` or `linkContainerClassName`

2019-01-14 01:47 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/index.js
> +  navbarStyle: PropTypes.string,
I'd rename to `navBarContainerClassName`

2019-01-14 01:47 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/index.js
> +  logoStyle: PropTypes.string,
I'd rename to `logoClassName`

2019-01-14 01:47 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +        <button className={`${styles.button} ${authButtonStyle}`} onClick={onLogout} type="button">
I'd rename to `authButtonClassName`

2019-01-14 01:47 UTC, nicolobruno commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +          <button className={`${styles.button} ${authButtonStyle}`} onClick={registerAction} type="button">
If this is only a redirection you can use tag `Link` of react-router-dom

2019-01-22 00:05 UTC, carlosbollero requested changes

2019-01-22 00:05 UTC, carlosbollero commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +          Log Out {/* TODO add i18n here*/}
Remember to add this translations

2019-01-22 00:05 UTC, carlosbollero commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +    <div className={`row ${styles.authButtons} ${authStyle}`}>
I'd move this className value to `defaultProps` so if anybody can define a different style for this.

2019-01-22 00:05 UTC, carlosbollero commented on generators/app/templates/src/app/components/Navbar/components/AuthButtons/index.js
> +        <button className={`${styles.button} ${authButtonStyle}`} onClick={onLogout} type="button">
Same here, i'd let the user set the style he wants for the nav bar.

2019-01-22 00:05 UTC, carlosbollero commented on generators/app/templates/src/app/components/Navbar/components/LinkList/index.js
> +function LinkList({ routesList, onChangeRoute, routesStyle, routeStyle }) {
To maintain consistency across the project, i'd  change styles props to `somethingClassName`.
In this case, it may be `routeClassName`

2019-01-22 00:05 UTC, carlosbollero commented on generators/app/templates/src/app/components/Navbar/components/LinkList/index.js
> +            <button
I'd extract this to a component that could receive either an image, a button, text or whatever the user wants. That component could encapsulate the `onClick` logic.

2019-01-22 00:05 UTC, carlosbollero commented on generators/app/templates/src/app/components/Navbar/index.js
> +      <div className={`row middle full-width ${styles.navbarContainer} ${navbarStyle}`}>
Move everything inside the render method to a layout component

2019-01-22 00:05 UTC, carlosbollero commented on generators/app/templates/src/app/components/Navbar/index.js
> +    // TODO implement
Remember to implement this, calling a function passed by props should be enough.
Same for the rest of the methods.

2019-01-22 00:05 UTC, carlosbollero commented on generators/app/templates/src/app/components/Navbar/index.js
> +    const isLoggedIn = this.loggedIn();
Is this necessary? Shouldn't be enough with a boolean prop `isLogged`.
This way we can map that prop to a redux state field or even other state container.

2019-01-22 00:05 UTC, carlosbollero commented on generators/app/templates/src/app/components/Navbar/templateRoutes.js
> +const NAVBAR_ROUTES = [
I don't think we need to have this routes constant inside the bootstrap as each project may define slightly different routes to the other. The navbar might have the logic to call a route change but the constant  won't be useful in the actual projects.

2019-04-01 14:56 UTC, closed without merging