Fix storybook and add camelCase feature
Wolox/react-bootstrap pull request #58
Opened 2019-01-10 20:27 UTC by HarryPerez

## Summary
Storybook

#### Features:
* Fixed Storybook 
* Moved Storybook to execute it only at bootstrap level (**It nos not generated with the project anymore**)
* Added camelCase feature in order to use styles **`className={styles.lobrunoNovimo}`** like:
 ```
 .lobruno-novimo {
  width: 100px;
}
```

2019-01-11 01:20 UTC, FrankIglesias requested changes

2019-01-11 01:20 UTC, FrankIglesias commented on generators/app/.storybook/.babelrc
> +}
add EOL

2019-01-11 01:20 UTC, FrankIglesias commented on generators/app/.storybook/webpack.config.js
> +
remove this line

2019-01-11 15:52 UTC, pabloccid requested changes

2019-01-11 15:52 UTC, pabloccid commented on generators/app/.storybook/webpack.config.js
> +const addCamelCaseToCSSModulesByHarry = (config) => {
Rename this function 👀

2019-01-11 15:52 UTC, pabloccid commented on generators/app/.storybook/webpack.config.js
> +const addCamelCaseToCSSModulesByHarry = (config) => {
Remove parentheses

2019-01-11 15:52 UTC, pabloccid commented on generators/app/.storybook/webpack.config.js
> +module.exports = baseConfig => addCamelCaseToCSSModulesByHarry(baseConfig);
```suggestion
module.exports = addCamelCaseToCSSModulesByHarry;
```

2019-01-29 16:23 UTC, FrankIglesias approved these changes

2019-01-29 20:31 UTC, pabloccid approved these changes

2019-01-29 20:31 UTC, merged