Login as main page
Wolox/react-bootstrap pull request #63
Opened 2019-01-23 18:09 UTC by rlajous

## Summary

-Main page is login now

2019-01-28 19:48 UTC, HarryPerez requested changes

2019-01-28 19:48 UTC, HarryPerez commented on generators/app/templates/src/app/components/Routes/components/AuthenticatedRoute.js
> +const DEFAULT_PUBLIC_ROUTE = Routes.HOME;
Is this ok? Home can not be the default public route. You need to be logged in order to access private routes. Check this.

2019-01-29 18:55 UTC, pabloccid reviewed
I think you inverted the logic. It was ok as it was. The login screen was already the default public route

2019-02-04 16:18 UTC, pabloccid commented on generators/app/templates/src/app/components/Routes/components/AuthenticatedRoute.js
>    initialized: PropTypes.bool,
dilit dis

2019-02-04 16:18 UTC, pabloccid commented on generators/app/templates/src/app/components/Routes/components/AuthenticatedRoute.js
>     * currentUser: false,
dilit dis

2019-02-04 16:25 UTC, pabloccid approved these changes

2019-02-04 17:47 UTC, HarryPerez approved these changes

2019-02-05 15:20 UTC, merged