Added check and echo
Wolox/react-bootstrap pull request #83
Opened 2019-09-04 16:54 UTC by rlajous

## Summary
- Added check if yoeman exist if not it installs it
## Screenshots

2019-09-05 02:23 UTC, FrankIglesias requested changes

2019-09-05 02:23 UTC, FrankIglesias commented on run.sh
> +if [ $? -eq 0 ]; then
check indentation

2019-09-11 14:51 UTC, damfinkel commented on run.sh
> +  echo YEOMAN not installed, installing now
"Yeoman not installed, installing now..."

Add the ... and uppercase is kind of ugly, use "Yeoman" instead of YEOMAN

2019-09-13 21:12 UTC, damfinkel approved these changes

2019-09-19 18:14 UTC, FrankIglesias approved these changes

2019-09-27 16:00 UTC, merged